# Generated by Django 5.2.17 on 2026-09-23 18:09

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('credential', 'Credential (expert application)'), ('avatar', 'Avatar')], db_index=True, max_length=30)),
                ('access', models.CharField(choices=[('private', 'Private'), ('public', 'Public read')], default='private', max_length=20)),
                ('file', models.FileField(max_length=300, upload_to=apps.files.models.attachment_storage_path)),
                ('original_name', models.CharField(max_length=254)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploader', 'sha256'], name='files_attac_uploade_69d597_idx'), models.Index(fields=['purpose', '-created_at'], name='files_attac_purpose_722a99_idx')],
            },
        ),
    ]
