# Generated by Django 5.2.17 on 2026-09-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='purpose',
            field=models.CharField(choices=[('credential', 'Credential (expert application)'), ('avatar', 'Avatar'), ('request_brief', 'Request brief attachment')], db_index=True, max_length=30),
        ),
    ]
