# Generated by Django 5.2.17 on 2026-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_attachment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='purpose',
            field=models.CharField(choices=[('credential', 'Credential (expert application)'), ('avatar', 'Avatar'), ('request_brief', 'Request brief attachment'), ('delivery', 'Order delivery file'), ('order_attachment', 'Order scope attachment'), ('message', 'Chat attachment')], db_index=True, max_length=30),
        ),
    ]
