# Generated by Django 5.2.17 on 2026-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_attachment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='purpose',
            field=models.CharField(choices=[('credential', 'Credential (expert application)'), ('avatar', 'Avatar'), ('request_brief', 'Request brief attachment'), ('delivery', 'Order delivery file'), ('order_attachment', 'Order scope attachment'), ('message', 'Chat attachment'), ('dispute_evidence', 'Dispute evidence')], db_index=True, max_length=30),
        ),
    ]
