# Generated by Django 5.2.17 on 2026-09-23 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=150)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('scope_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('superseded', 'Superseded (reassigned)')], db_index=True, default='pending', max_length=12)),
                ('decline_reason', models.CharField(blank=True, max_length=200)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('decided_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_assignments', to='service_requests.servicerequest')),
            ],
            options={
                'indexes': [models.Index(fields=['expert', 'status'], name='assignments_expert__29a1c9_idx'), models.Index(fields=['request', 'status'], name='assignments_request_4439f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PoolInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('expected_amount', models.BigIntegerField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=200)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_invitations', to='service_requests.servicerequest')),
            ],
            options={
                'indexes': [models.Index(fields=['expert', 'status'], name='assignments_expert__6b92ec_idx'), models.Index(fields=['request', 'status'], name='assignments_request_1a39de_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'expert'), name='uniq_pool_invitation_per_expert')],
            },
        ),
    ]
