# Generated by Django 5.2.17 on 2026-09-24 15:37

from decimal import Decimal

from django.db import migrations, models


def seed_singleton(apps, schema_editor):
    """Seed the singleton from the historical module constants (BR-17/18,
    BR-30/40 defaults) — behavior-verified by the existing suites."""
    PlatformConfig = apps.get_model("core", "PlatformConfig")
    PlatformConfig.objects.get_or_create(
        pk=1,
        defaults={
            "open_commission_rate": 0.1500,
            "managed_commission_rate": 0.2000,
            "min_offer_minor": 500,
            "payout_min_minor": 1000,
            "dispute_window_days": 7,
            "default_currency": "USD",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('open_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5)),
                ('managed_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5)),
                ('min_offer_minor', models.BigIntegerField(default=500)),
                ('payout_min_minor', models.BigIntegerField(default=1000)),
                ('dispute_window_days', models.PositiveSmallIntegerField(default=7)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Platform configuration',
                'verbose_name_plural': 'Platform configuration',
            },
        ),        migrations.RunPython(seed_singleton, migrations.RunPython.noop),
    ]
