# Generated by Django 5.2.17 on 2026-09-23 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_alter_attachment_purpose'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('open', 'Open marketplace'), ('managed', 'Managed service')], db_index=True, default='open', max_length=10)),
                ('category', models.CharField(choices=[('tutoring', '1:1 tutoring sessions'), ('concept_coaching', 'Concept coaching'), ('problem_walkthrough', 'Guided problem walkthrough'), ('writing_feedback', 'Writing feedback & coaching'), ('code_review', 'Code review & mentoring'), ('exam_prep', 'Exam preparation'), ('mentorship', 'Ongoing mentorship'), ('other', 'Other legitimate help')], default='tutoring', max_length=30)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed price'), ('hourly', 'Hourly rate')], default='fixed', max_length=10)),
                ('budget_min', models.BigIntegerField(blank=True, null=True)),
                ('budget_max', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('preferred_schedule', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Receiving offers'), ('matched', 'Expert selected'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected (managed review)'), ('in_review', 'In review (managed)'), ('pooled', 'Sent to expert pool (managed)'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=15)),
                ('integrity_attested_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_policy_version', models.CharField(blank=True, max_length=20)),
                ('quote_amount', models.BigIntegerField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=200)),
                ('attachments', models.ManyToManyField(blank=True, related_name='service_requests', to='files.attachment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='skill_requests', to='taxonomy.taxonomyterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='taxonomy.taxonomyterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='service_req_status_6f62f5_idx'), models.Index(fields=['student', '-created_at'], name='service_req_student_db2d3e_idx'), models.Index(fields=['mode', 'status'], name='service_req_mode_253a7d_idx')],
            },
        ),
    ]
