# Generated by Django 5.2.17 on 2026-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
