# Generated by Django 5.2.17 on 2026-09-24 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('off_platform', 'Off-platform payment/contact'), ('abuse', 'Abusive language'), ('integrity', 'Academic integrity concern'), ('spam', 'Spam'), ('other', 'Other')], max_length=20)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('message', 'reported_by'), name='one_open_report_per_message_per_user')],
            },
        ),
    ]
