# Generated by Django 5.2.17 on 2026-09-24 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0005_attachment_legal_hold_alter_attachment_purpose'),
        ('orders', '0007_deadlineproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('quality_below_expectations', 'Quality below expectations'), ('expert_unresponsive', 'Expert unresponsive'), ('deadline_missed', 'Deadline missed'), ('scope_disagreement', 'Scope disagreement'), ('payment_issue', 'Payment issue'), ('integrity_concern', 'Academic integrity concern'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('prior_order_status', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('awaiting_response', 'Awaiting response'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('refund_student_full', 'Full refund to student'), ('refund_student_partial', 'Partial refund to student'), ('release_expert', 'Release to expert'), ('split', 'Split student/expert'), ('no_fault_close', 'No fault — resume order')], max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ManyToManyField(blank=True, related_name='dispute_evidence', to='files.attachment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
