# Generated by Django 5.2.17 on 2026-09-23 18:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('expert_id', models.BigIntegerField()),
                ('expert_name', models.CharField(max_length=150)),
                ('expert_slug', models.SlugField(blank=True, max_length=180)),
                ('source', models.CharField(choices=[('open_bid', 'Open marketplace offer'), ('managed_pool', 'Managed — expert pool invitation'), ('managed_direct', 'Managed — direct assignment')], db_index=True, max_length=20)),
                ('offer_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5)),
                ('commission_amount', models.BigIntegerField(default=0)),
                ('expert_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('active', 'Active'), ('delivered', 'Delivered'), ('revision_requested', 'Revision requested'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='awaiting_payment', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('revisions_allowed', models.PositiveSmallIntegerField(default=2)),
                ('revisions_used', models.PositiveSmallIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('auto_approve_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_due_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
