# Generated by Django 5.2.17 on 2026-09-23 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_attachment_purpose'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Order created'), ('payment_confirmed', 'Payment confirmed'), ('delivered', 'Work delivered'), ('revision_requested', 'Revision requested'), ('redelivered', 'Revision delivered'), ('approved', 'Delivery approved'), ('auto_approved', 'Auto-approved (72h elapsed)'), ('completed', 'Order completed'), ('cancelled', 'Order cancelled'), ('dispute_opened', 'Dispute opened')], db_index=True, max_length=25)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted (awaiting review)'), ('approved', 'Approved'), ('revision_requested', 'Revision requested')], db_index=True, default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_source', models.CharField(blank=True, max_length=10)),
                ('attachments', models.ManyToManyField(blank=True, related_name='deliveries', to='files.attachment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.order')),
            ],
            options={
                'ordering': ['revision_number'],
                'constraints': [models.UniqueConstraint(fields=('order', 'revision_number'), name='uniq_delivery_revision_per_order')],
            },
        ),
    ]
