# Generated by Django 5.2.17 on 2026-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_attachment_purpose'),
        ('orders', '0003_orderevent_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='orders', to='files.attachment'),
        ),
    ]
