# Generated by Django 5.2.17 on 2026-09-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order created'), ('payment_confirmed', 'Payment confirmed'), ('delivered', 'Work delivered'), ('revision_requested', 'Revision requested'), ('redelivered', 'Revision delivered'), ('approved', 'Delivery approved'), ('auto_approved', 'Auto-approved (72h elapsed)'), ('completed', 'Order completed'), ('cancelled', 'Order cancelled'), ('dispute_opened', 'Dispute opened'), ('deadline_reminded', 'Deadline reminder sent')], db_index=True, max_length=25),
        ),
    ]
