# Generated by Django 5.2.17 on 2026-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_open_dispute',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order created'), ('payment_confirmed', 'Payment confirmed'), ('delivered', 'Work delivered'), ('revision_requested', 'Revision requested'), ('redelivered', 'Revision delivered'), ('approved', 'Delivery approved'), ('auto_approved', 'Auto-approved (72h elapsed)'), ('completed', 'Order completed'), ('cancelled', 'Order cancelled'), ('dispute_opened', 'Dispute opened'), ('dispute_resolved', 'Dispute resolved'), ('overdue_flagged', 'Overdue — flagged for follow-up'), ('deadline_proposed', 'Deadline proposal sent'), ('deadline_extended', 'Deadline extended (proposal accepted)'), ('deadline_reminded', 'Deadline reminder sent')], db_index=True, max_length=25),
        ),
    ]
