# Generated by Django 5.2.17 on 2026-09-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_has_open_dispute_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by_id', models.BigIntegerField()),
                ('proposed_due_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_proposal', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
