# Generated by Django 5.2.17 on 2026-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_deadlineproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Order created'), ('payment_confirmed', 'Payment confirmed'), ('delivered', 'Work delivered'), ('revision_requested', 'Revision requested'), ('redelivered', 'Revision delivered'), ('approved', 'Delivery approved'), ('auto_approved', 'Auto-approved (72h elapsed)'), ('completed', 'Order completed'), ('cancelled', 'Order cancelled'), ('dispute_opened', 'Dispute opened'), ('dispute_resolved', 'Dispute resolved'), ('overdue_flagged', 'Overdue — flagged for follow-up'), ('deadline_proposed', 'Deadline proposal sent'), ('deadline_extended', 'Deadline extended (proposal accepted)'), ('deadline_reminded', 'Deadline reminder sent'), ('auto_approve_warned', 'Auto-approval warning sent')], db_index=True, max_length=25),
        ),
    ]
