# Generated by Django 5.2.17 on 2026-09-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile'),
        ('files', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='expert_application', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('draft', 'Draft (not yet submitted)'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
                ('display_name', models.CharField(max_length=150, verbose_name='professional/display name')),
                ('headline', models.CharField(max_length=120)),
                ('bio', models.TextField(max_length=2000, verbose_name='bio / expertise description')),
                ('expertise_summary', models.CharField(max_length=500, verbose_name='expertise summary')),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('qualifications', models.CharField(blank=True, max_length=1000, verbose_name='qualifications')),
                ('languages', models.CharField(blank=True, help_text="Comma-separated, e.g. 'English, Urdu'.", max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('availability_note', models.CharField(blank=True, max_length=300)),
                ('certified_18_plus', models.BooleanField(default=False)),
                ('integrity_acknowledged', models.BooleanField(default=False, help_text="Acknowledged the tutor guidelines: 'You are a teacher, not a ghostwriter.'")),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resubmission_count', models.PositiveSmallIntegerField(default=0)),
                ('credentials', models.ManyToManyField(blank=True, related_name='expert_applications', to='files.attachment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_reviews', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='application_skills', to='taxonomy.taxonomyterm')),
                ('subjects', models.ManyToManyField(blank=True, related_name='expert_applications', to='taxonomy.taxonomyterm')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='experts_exp_status_b9cce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='expert_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('expertise_summary', models.CharField(blank=True, max_length=500)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('qualifications', models.CharField(blank=True, max_length=1000)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('paused', 'Paused (not accepting new work)')], db_index=True, default='available', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Opt-out of the public directory regardless of approval state.')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ForeignKey(blank=True, limit_choices_to={'purpose': 'avatar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_of', to='files.attachment')),
                ('skills', models.ManyToManyField(blank=True, related_name='profile_skills', to='taxonomy.taxonomyterm')),
                ('subjects', models.ManyToManyField(blank=True, related_name='expert_profiles', to='taxonomy.taxonomyterm')),
            ],
            options={
                'indexes': [models.Index(fields=['is_public', 'availability'], name='experts_exp_is_publ_2d87c1_idx'), models.Index(fields=['-rating_avg'], name='experts_exp_rating__be037f_idx')],
            },
        ),
    ]
