# Generated by Django 5.2.17 on 2026-09-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.CharField(blank=True, help_text='Learning context for experts (never graded-work instructions).', max_length=1000, verbose_name='short bio')),
                ('interests', models.ManyToManyField(blank=True, limit_choices_to={'kind__in': ['subject', 'skill']}, related_name='interested_students', to='taxonomy.taxonomyterm')),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
    ]
