# Generated by Django 5.2.17 on 2026-09-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='service_requests.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['request', 'status'], name='bidding_off_request_2ba7a1_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['expert', 'status'], name='bidding_off_expert__076b74_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('request', 'expert'), name='uniq_offer_per_expert_per_request'),
        ),
    ]
