# Generated by Django 5.2.17 on 2026-09-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('category', 'Category'), ('subject', 'Subject'), ('skill', 'Skill'), ('tag', 'Tag')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, max_length=170)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent (categories may contain subjects).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.taxonomyterm')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['parent', 'kind'], name='taxonomy_ta_parent__06f058_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='uniq_term_kind_slug')],
            },
        ),
    ]
